export const AmenityList = [
    "24 Hour Reception",
    "Bar",
    "Cafe",
    "Childcare centre",
    "Concierge Desk",
    "Conference Room",
    "Elevator",
    "Health Club",
    "In-house Doctor",
    "Laundry",
    "Lounge Area",
    "Luggage Room",
    "Onsite Healthcate",
    "Parking Area",
    "Public Room",
    "Restaurant",
    "Room Service",
    "Sauna",
    "Shops",
    "Spa",
    "Swimming Pool",
    "Travel Desk",
  ];
